import tempfile
import unittest
from pathlib import Path

from app import database
from app.postgres_migration import inspect_sqlite, render_postgres_schema


class PostgresMigrationSnapshotTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.db_path = Path(self.temp.name) / "kindred.db"
        self.old_db_path = database.DB_PATH
        self.old_upload_dir = database.UPLOAD_DIR
        old_conn = getattr(database._local, "conn", None)
        if old_conn is not None:
            old_conn.close()
        database._local.conn = None
        database.DB_PATH = self.db_path
        database.UPLOAD_DIR = Path(self.temp.name) / "uploads"
        database.init_db()

    def tearDown(self):
        conn = getattr(database._local, "conn", None)
        if conn is not None:
            conn.close()
        database._local.conn = None
        database.DB_PATH = self.old_db_path
        database.UPLOAD_DIR = self.old_upload_dir
        self.temp.cleanup()

    def test_snapshot_captures_current_schema_and_postgres_types(self):
        database.save_profile({
            "id": "profile-1",
            "name": "Profile",
            "age": 30,
            "gender": "x",
            "seeking": "x",
            "embedding": b"vector",
        })

        snapshot = inspect_sqlite(self.db_path)
        tables = {table.name: table for table in snapshot.tables}
        self.assertEqual(snapshot.schema_version, 13)
        self.assertIn("weight_learning_events", tables)
        self.assertEqual(tables["profiles"].row_count, 1)
        self.assertEqual(tables["profiles"].columns[16].sqlite_type, "BLOB")

        ddl = "\n".join(render_postgres_schema(snapshot))
        self.assertIn('"embedding" BYTEA', ddl)
        self.assertIn("GENERATED BY DEFAULT AS IDENTITY", ddl)


if __name__ == "__main__":
    unittest.main()
